include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures

    - use_build_context_synchronously
    - valid_regexps
    # Add more rules as needed
